config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'exchange_rate#index'
  get 'difference', to: 'exchange_rate#difference'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exchange_rate.rb
# frozen_string_literal: true

class ExchangeRate < ApplicationRecord
    validates :current_rate, presence: true, uniqueness: { 
        scope: [:current_rate, :parse_at]
    }

    validates :current_value, presence: true
    validates :parse_at, presence: true

    enum current_rate: {
        rub_usd: 'rub_usd',
        rub_eur: 'rub_eur',
        rub_cny: 'rub_cny'
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchange_rate_controller.rb
class ExchangeRateController < ApplicationController
  def index
    date_end = Date.current
    date_start = date_end - 1.month

    @columns = ExchangeRateMapper.new(date_start, date_end).call
  end

  def difference
    @diffs = DiffRatesMapper.new.call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchange_rate/difference.html.slim
.container
  h2 Разница курсов

  table border="1" cellpadding="5" cellspacing="0" style='border-collapse: collapse;'
    thead
      tr
        th Валюта
        th 4 недели назад
        th 3 недели назад
        th позапрошлая неделя
        th прошлая неделя
    tbody
      // - cache('diff', expires_at: Date.current.end_of_day) do
      - @diffs.each do |rate_name, diffs|
        tr
          td = rate_name
          - diffs.each do |value, percent|
            td 
              - if value.present?
                  | #{number_with_precision(value, precision: 2)} ₽&nbsp;
                  | #{number_to_percentage(percent, format: "(%n %)")}
              - else
                | Нет данных

app/views/exchange_rate/index.html.slim
.container
  h2 Курсы валют за месяц
  #rates

  - if @columns.present?
    ruby:
      js_graph = graph_generate('rates',
        data: {
          x: 'x',
          columns: @columns
        },
        axis: {
          x: {
              type: 'timeseries',
              tick: {
                  format: '%Y-%m-%d'
              }
          }
        }
      )

    = javascript_tag
      = js_graph

  - else
    | Нет данных

app/views/layouts/application.html.slim
doctype html
html
  head
    title Exchange Rates
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag

  body
    = render 'shared/menu'
    = yield

app/views/shared/_menu.html.slim
| Меню сайта: 
= link_to 'Главная', root_path
| , 
= link_to 'Разница курсов', difference_path